### ISSUE TITLE
Enable https

### ISSUE THREAD

**Issue by AntoineDao** [pollination/k8s-cluster-management#10]
Some useful docs for Knative and HTTPS [here](https://github.com/knative/docs/blob/master/serving/using-an-ssl-cert.md)

**Comment by AntoineDao** [comment]
Seems using [`cert-manager`](https://github.com/jetstack/cert-manager/) will be helpful to generate certificates and automatically renew them.

**Comment by AntoineDao** [comment]
And will use [this document](https://github.com/knative/docs/blob/master/serving/using-cert-manager-on-gcp.md) to guide certification generation and use in Knative.

**Comment by AntoineDao** [comment]
[This](https://istio.io/blog/2019/custom-ingress-gateway/) is also helpful.

**Comment by mostaphaRoudsari** [comment]
> And will use [this document](https://github.com/knative/docs/blob/master/serving/using-cert-manager-on-gcp.md) to guide certification generation and use in Knative.

Are we still going to use Knative or the plan is to replace it with Argo?

**Comment by AntoineDao** [comment]
Yep this was before knative removal so is irrelevant.
