### ISSUE TITLE
Set up http microservice template

### ISSUE THREAD

**Issue by AntoineDao** [pollination/k8s-cluster-management#7]
I think  I'm happy to say we're going to go with Knative as it integrates seamlessly with istio and offers a neat eventing abstraction. We now need a basic configuration and flask app template to facilitate development. The following will be required for this issue to be complete:

- [x] ~Knative Build template~ CI/CD - Use Travis for now
- [x] Knative Service template
- [x] Flask app template

**Comment by AntoineDao** [comment]
Knative serving template set up:

https://github.com/pollination/example-service/releases/tag/v1.0.3

**Comment by AntoineDao** [comment]
## CI/CD
Set up using Travis here: https://github.com/pollination/example-service/releases/tag/v1.0.1

**Comment by AntoineDao** [comment]
# Flask Template
Initial release proposed here: https://github.com/pollination/example-service/releases/tag/v1.1.0

**Comment by AntoineDao** [comment]
@mostaphaRoudsari I am going to move this into review while you test it out and see what you'd like to change.

**Comment by mostaphaRoudsari** [comment]
## API Documentation

@AntoineDao, as discussed today we most likely want to consider support for openapi3 instead of openapi2 (aka swagger).

**Comment by AntoineDao** [comment]
I reckon we're pretty happy with the current setup in model and grid services.
